---
# 
# Install Couchbase cluster main node
#
# @codyhalovich | HootSuite Media Inc.
# http://hootsuite.com
#

- name: Couchbase Installation
  hosts: cbmain
  vars_files:
  - [ ../vars/all.yml ]
  user: ubuntu
  sudo: yes
   
  tasks:

  - name: download Couchbase package
    get_url: url=http://packages.couchbase.com/releases/2.2.0/couchbase-server-enterprise_2.2.0_x86_64_openssl098.deb dest=~ubuntu/.
 
  - name: Install dependencies
    apt: pkg=libssl0.9.8 state=present

  - name: Install Couchbase .deb file on node
    shell: dpkg -i ~ubuntu/couchbase-server-enterprise_2.2.0_x86_64_openssl098.deb
     
  - name: Add data dir to EBS & chown
    file: path=/ebs1/couchbase state=present
        
  - name: chown data dir to couchbase
    shell: chown couchbase:couchbase /ebs1/couchbase

  - name: Initialize node with data-dir
    shell: /opt/couchbase/bin/couchbase-cli node-init -c 127.0.0.1:8091 --node-init-data-path=/ebs1/couchbase -u ${admin_user} -p ${admin_password}

  - name: Initialize Cluster
    shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 -u ${admin_user} -p ${admin_password} --cluster-init-username=${admin_user} --cluster-init-password=${admin_password} --cluster-init-port=8091 --cluster-init-ramsize=${cluster_ram_quota}
    
  - name: Set hostname for main node
    shell: curl -v -X POST -u Administrator:5up3rm4n $inventory_hostname:8091/node/controller/rename -d hostname=$inventory_hostname

  - name: Initialize Cluster
    shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 -u ${admin_user} -p ${admin_password} --cluster-init-username=${admin_user} --cluster-init-password=${admin_password} --cluster-init-port=8091 --cluster-init-ramsize=${cluster_ram_quota}

#  - name: Create shell script for configuring all nodes
#    action: template src=couchbase-add-node.j2 dest=/tmp/addnodes.sh mode=750
  
#  - name: Launch config script
#    action: shell /tmp/addnodes.sh
  
#  - name: Rebalance the cluster
#    shell: /opt/couchbase/bin/couchbase-cli rebalance -c 127.0.0.1:8091 -u ${admin_user} -p ${admin_password}      
  
  - name: create bucket ${bucket_name} with ${num_replicas} replicas
    shell: /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=${bucket_name} --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=${bucket_ram_quota} --bucket-replica=${num_replicas} -u ${admin_user} -p ${admin_password}
